[package]
name = "ash"
version = "0.1.0"
authors = ["Mårten Kongstad <marten.kongstad@sony.com>"]
edition = "2018"

[dependencies]
regex = "1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
